### ISSUE TITLE
Unable to Query for Description on Type

### ISSUE THREAD

**Issue by adavis** [pgutkowski/KGraphQL#12]
I have a very simple test class and I've added a description to it in the `schema`:

```
data class Player(val name: String = "", val age: Int = 0)

type<Player> {
    description = "A NBA Player on a Team"
}
```

But when I query for this description with the following:
```
query {
	__schema {
		types {
	        name
	        kind
	        description
	    }
	}
}
```

It's always *empty*. Is there something I need to do differently to be able to inspect the descriptions that I set in the schema?

**Comment by pgutkowski** [comment]
Hi @adavis!

Thank you for your bug report. I'm sorry that it took so long for me to respond. It's weird, because I've added test in https://github.com/pgutkowski/KGraphQL/commit/11f7a5585a5a4aa8afe26929bfdba77f44feabbe and it passes. Besides, demo application has description field on many types eg [PlayerApiConfigurator.kt has description](https://github.com/pgutkowski/KGraphQL-NBA2012/blob/master/src/main/kotlin/com/github/pgutkowski/kgraphqlnba/player/PlayerApiConfigurator.kt#L35) producing [this json](https://kql-nba2012.herokuapp.com/api?query=%7B%20__type(name%3A%20%22Player%22)%7Bdescription%2C%20fields%7Bname%2C%20type%7Bkind%2C%20name%2C%20ofType%7Bname%7D%7D%20%7D%7D%20%7D).

Please provide more details (like some test case or detailed steps to reproduce) so we can solve your issue.

**Comment by adavis** [comment]
I totally don't know why it wasn't working. But I just ran another query on my current sample app and it worked. If I can reproduce the original problem, I'll create a new issue. 🤷🏽‍♀️
